import { Button, VerticalBox } from "std-widgets.slint";
export component MainWindow {
    callback ok_button_clicked();
    width: 800px;
    height: 480px;
    VerticalBox {
        width: 100%;
        Text {
            text: "Hello World!";
            font-size: 24px;
            color: green;
            horizontal-alignment: center;
        }
        Image {            
            source: @image-url("slint-logo-full-light.svg");
        }
        HorizontalLayout {
            alignment: center; 

            Button {
                width: 100px;
                height: 200px;
                text: "OK!";
                clicked => { ok_button_clicked(); }
            }
            Rectangle { background: yellow; horizontal-stretch: 1; }
        }
    }
}
